version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=calendaruser
      - MYSQL_PASSWORD=12123434example
      - MYSQL_DATABASE=calendarDB
    depends_on:
      - mysql
    entrypoint: /bin/sh -c "until nc -z -v -w30 mysql 3306; do echo 'Waiting for MySQL...'; sleep 5; done; npm start"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: calendarDB
      MYSQL_USER: calendaruser
      MYSQL_PASSWORD: 12123434example
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

