receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  transform:
    trace_statements:
      - context: resource
        statements:
          - set(attributes["service.name"], "github-actions")

exporters:
  logging: {}

  otlp:
    endpoint: http://a1174a7133ac0404482e155f3a76871e-1220444037.us-east-1.elb.amazonaws.com:4317
    tls:
      insecure: true

  # prometheus:
  #   endpoint: "z0.0.0.0:9464"

  # loki:
  #   endpoint: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
  #   labels:
  #     job: "otel-collector"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch,trasform]
      exporters: [otlp]

    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [prometheus, logging]

    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [loki, logging]
