receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging: {}

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  # prometheus:
  #   endpoint: "z0.0.0.0:9464"

  # loki:
  #   endpoint: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
  #   labels:
  #     job: "otel-collector"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [prometheus, logging]

    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [loki, logging]
