mode: deployment

image:
  repository: otel/opentelemetry-collector  # Add this line

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: otel.nadav.online
      paths:
        - path: /
          pathType: Prefix
          port: 4318  # Add the port here
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/acme-dns01-provider: cloudflare
  tls:
    - hosts:
        - otel.nadav.online
      secretName: otel-tls

config:
  exporters:
    otlp:
      endpoint: "tempo:4317"  # Change port to 4317 for gRPC
      tls:
        insecure: true
  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [otlp]