receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  attributes:
    actions:
      - key: service.name
        value: "github-actions"
        action: upsert  # Adds the attribute or updates it if it already exists

exporters:
  otlphttp:
    endpoint: http://a1174a7133ac0404482e155f3a76871e-1220444037.us-east-1.elb.amazonaws.com:4318/v1/traces
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlphttp]