global:
  replicaCount: 1

# Namespace where resources will be deployed
namespace: production

# Backend configuration
backend:
  ingress:
    hostname: prod-api.grandnerds.com

# Frontend configuration
frontend:
  ingress:
    hostname: prod-calendar.grandnerds.com
    
openproject:
  install: false
  
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/acme-challenge-type: dns01
      cert-manager.io/acme-dns01-provider: cloudflare
    host: openproject.grandnerds.com
    tls:
      enabled: true
      secretName: openproject-tls
  
  openproject:
    host: openproject.grandnerds.com
    admin_user:
      password: "hihihihi"
      password_reset: "false"
      name: "hahahaha"
      mail: "faizan.anwar@venturenox.com"
  
  persistence:
    enabled: true
    accessModes:
      - "ReadWriteOnce"
    size: "1Gi"
    storageClassName: "gp2"
