apiVersion: v2
name: my-app
description: A Helm chart for a web application with frontend and backend components
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: App Team
    email: faizi@faizi.com
dependencies:
- name: mysql
  version: "12.2.2"
  repository: "https://charts.bitnami.com/bitnami"
# - name: openproject
#   version: "9.10.0"
#   repository: https://charts.openproject.org
#   condition: openproject.install