{{- if .Values.backend.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-app.backend.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.backend.ingress.className | default "nginx" }}
  {{- if .Values.backend.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.backend.ingress.hostname | quote }}
    secretName: {{ include "my-app.backend.name" . }}-tls
  {{- end }}
  rules:
  - host: {{ .Values.backend.ingress.hostname | quote }}
    http:
      paths:
      - path: /
        pathType: {{ .Values.backend.ingress.pathType | default "Prefix" }}
        backend:
          service:
            name: {{ include "my-app.backend.name" . }}
            port:
              number: 80
{{- end }}