apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.frontend.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  ports:
  - port: 80
    targetPort: {{ .Values.frontend.service.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend