apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app.fullname" . }}-db-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.backend.env.MYSQL_USER | b64enc | quote }}
  password: {{ .Values.backend.env.MYSQL_PASSWORD | b64enc | quote }}