name: Build and Push Backend & Frontend to ECR

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    name: Build and Push Docker Images to ECR
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set SHORT_SHA Environment Variable
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV
      
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set your desired Node.js version
  
      - name: Install dependencies
        run: |
          npm init -y  # Initialize a new Node.js project (if not already present)
          npm install @opentelemetry/api @opentelemetry/sdk-node @opentelemetry/exporter-otlp-http @opentelemetry/sdk-trace-base
  
      - name: Run OpenTelemetry script
        run: |
          node -e "
            const { NodeSDK } = require('@opentelemetry/sdk-node');
            const { OTLPTraceExporter } = require('@opentelemetry/exporter-otlp-http');
            const { SimpleSpanProcessor } = require('@opentelemetry/sdk-trace-base');
  
            const sdk = new NodeSDK({
              traceExporter: new OTLPTraceExporter({
                url: 'http://otel.nadav.online:4318/v1/traces',
              }),
              spanProcessor: new SimpleSpanProcessor(new OTLPTraceExporter({
                url: 'http://otel.nadav.online:4318/v1/traces',
              })),
            });
  
            sdk.start()
              .then(() => {
                console.log('OpenTelemetry initialized');
              })
              .catch(err => {
                console.error('Error initializing OpenTelemetry SDK:', err);
              });
          "

      # - name: Build and Push Backend Image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     BACKEND_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY_BACKEND }}
      #   run: |
      #     docker build -t $BACKEND_REPOSITORY:${{ env.SHORT_SHA }} ./backend
      #     docker push $BACKEND_REPOSITORY:${{ env.SHORT_SHA }}

      # - name: Build and Push Frontend Image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     FRONTEND_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY_FRONTEND }}
      #   run: |
      #     docker build -t $FRONTEND_REPOSITORY:${{ env.SHORT_SHA }} ./frontend
      #     docker push $FRONTEND_REPOSITORY:${{ env.SHORT_SHA }}

      # - name: Install OpenTelemetry Collector
      #   run: |
      #     curl -L https://github.com/open-telemetry/opentelemetry-collector-releases/releases/latest/download/otelcol-linux-amd64 -o /usr/local/bin/otelcol
      #     chmod +x /usr/local/bin/otelcol

      # - name: Start OpenTelemetry Collector
      #   run: |
      #     otelcol --config=/otel-config.yaml &

      # - name: Run Build Step
      #   run: |
      #     curl -X POST "https://otel.nadav.online/v1/traces" -H "Content-Type: application/json" -d '{
      #       "name": "GitHub Actions Build",
      #       "startTimeUnixNano": "$(date +%s%N)",
      #       "endTimeUnixNano": "$(date +%s%N)"
      #     }'

