name: Build and Push Docker Images

on:
#   push:
#     branches: 
#     - main
#   pull_request:
#     branches:  
#     - main 
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set SHORT_SHA Environment Variable
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            faizananwar532/calendar-backend:latest
            faizananwar532/calendar-backend:${{ env.SHORT_SHA }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            faizananwar532/calendar-frontend:latest
            faizananwar532/calendar-frontend:${{ env.SHORT_SHA }}
